project_id = "pyozqcxrkptaagonrrwc"

[functions.submit-service-request]
verify_jwt = false

[functions.list-users]
verify_jwt = false

[functions.submit-contact-message]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.send-reminders]
verify_jwt = false
